clusterDomain: "se6099.opencraft.hosting"

ingress-nginx:
  enabled: true
  controller:
    config:
      proxy-body-size: 100m

cert-manager:
  enabled: false
  installCRDs: true
  email: "gabor@opencraft.com"

elasticsearch:
  enabled: false

metricsserver:
  enabled: false

vpa:
  enabled: false

opensearch:
  enabled: false

prometheusstack:
  enabled: false

k8sdashboard:
  enabled: true

openfaas:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: openfaas.se6099.opencraft.hosting  # Replace with gateway.example.com if public-facing
        serviceName: gateway
        servicePort: 8080
        path: /
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true" 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"