---
{{- $ca := genCA "elasticca" 1825 }}
{{- $cn := printf "harmony-search-cluster.%s.svc.cluster.local" .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $cn) 1825 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: search-cluster-certificates-elasticsearch
type: Opaque
data:
  "ca.crt": {{ $ca.Cert | b64enc | toYaml | indent 4}}
  "tls.key": {{ $cert.Key | b64enc | toYaml | indent 4}}
  "tls.crt": {{ print $cert.Cert | b64enc | toYaml | indent 4}}
  "chain.crt": {{ print $cert.Cert $ca.Cert | b64enc | toYaml | indent 4}}
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
type: Opaque
data:
  "password": {{ randAlphaNum 32 | b64enc | quote }}
