# Disable HTTPS cert provisioning for testing with minikube
cert-manager:
   enabled: false

traefik:
  # All these needed for local development
  service:
    spec:
      type: NodePort
  ports:
    web:
      hostPort: 80
    websecure:
      hostPort: 443

clusterDomain: harmony.test

elasticsearch:
  enabled: true

   # TODO: move this to a separate PR
   # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  volumeClaimTemplate:
    resources:
      requests:
        storage: 8Gi
  replicas: 1

opensearch:
  enabled: false

   # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  persistence:
    size: 8Gi

prometheusstack:
  enabled: true

headlamp:
  enabled: false
