{{ if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-global
spec:
  acme:
    {{- if index .Values "cert-manager" "email" }}
    email: {{ index .Values "cert-manager" "email" }}
    {{- end }}
    preferredChain: ""
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-global
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class:  {{ index .Values "ingress-nginx" "controller" "ingressClass" }}
{{ end }}
