# This service, which is always enabled, allows you to do basic health checks of your cluster and the Ingress Controller
# Service by accessing /cluster-echo-test via HTTP on any hostname associated with your cluster.
{{- if index .Values "ingress-nginx" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster-echo-app
  name: cluster-echo-service
spec:
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 8080
  selector:
    app: cluster-echo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-echo-app
  name: cluster-echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-echo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cluster-echo-app
    spec:
      containers:
      - image: mendhak/http-https-echo:25
        name: cluster-echo
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-echo-test
spec:
  ingressClassName: {{ (index .Values "ingress-nginx" "controller" "ingressClass") }}
  rules:
  - host: {{ .Values.clusterDomain }}
    http:
      paths:
      - path: /cluster-echo-test
        pathType: Prefix
        backend:
          service:
            name: cluster-echo-service
            port:
              number: 8080
{{- end }}
