apiVersion: v2
name: harmony-chart
description: A Helm chart for deploying multiple Open edX instances onto Kubernetes using Tutor
type: application
# This is the chart version. This version number should be incremented each time you make changes to the chart and its
# templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
# This is the version number of the application being deployed. This version number should be incremented each time you
# make changes to the application. Versions are not expected to follow Semantic Versioning. They should reflect the
# version the application is using. It is recommended to use it with quotes.
#
# In our case, this represents the version of Tutor that this chart is compatible with.
appVersion: "14.1.1"

dependencies:
# This is just info for the "helm dependency update" command, which will update the ./charts/ directory when run, using
# this information.
- name: ingress-nginx
  version: "4.4.2"
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.enabled

- name: cert-manager
  version: "1.11.0"
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled

- name: elasticsearch
  version: "7.17.3"
  condition: elasticsearch.enabled
  repository: https://helm.elastic.co

- name: metrics-server
  version: "~3.8.3"
  repository: https://kubernetes-sigs.github.io/metrics-server/
  alias: metricsserver
  condition: metricsserver.enabled

- name: vertical-pod-autoscaler
  version: "~6.0.3"
  repository: https://cowboysysop.github.io/charts/
  alias: vpa
  condition: vpa.enabled
