---
{{- $ca := genCA "elasticca" 1825 }}
{{- $cert := genSignedCert "elasticsearch-master.{{ Release.Namespace }}.local" nil (list "elasticsearch-master.{{ Release.Namespace }}.local") 1825 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-certificates
type: Opaque
data:
  "ca.crt": {{ $ca.Cert | b64enc | toYaml | indent 4}}
  "tls.key": {{ $cert.Key | b64enc | toYaml | indent 4}}
  "tls.crt": {{ print $cert.Cert $ca.Cert | b64enc | toYaml | indent 4}}
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
type: Opaque
data:
  "password": {{ randAlphaNum 32 | b64enc | quote }}
