name: Renovate

on:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v40.1.12
      with:
        token: ${{ secrets.RENOVATE_PATH }}
        configurationFile: renovate.json
      env:
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        LOG_LEVEL: info
        RENOVATE_ONBOARDING: false
